import os
import datetime


class NameNotSpecificationError(Exception):
    def __init__(self, name: str) -> None: ...

    def __str__(self) -> str: ...


class PathNotFoundError(Exception):
    def __init__(self) -> None: ...

    def __str__(self) -> str: ...


class PathNotFoundError(Exception):
    def __init__(self, name: str) -> None: ...

    def __str__(self) -> str: ...


class create(object):
    def __init__(self, **kw) -> None: ...

    def createDir(self, dirName: str) -> None: ...

    def createFile(self, path: str, name: str, value: str) -> None: ...
